title:              ME 495 - Embedded Systems in Robotics
description:        ""
url:                "http://localhost:4000"
baseurl:            /eecs-495-site

markdown:           kramdown
permalink:          pretty